name: ai_tool_store_client
description: "AI Tool Store - Flutter Client"
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.2
  intl: ^0.19.0

  # State Management (Riverpod)
  flutter_riverpod: ^2.5.1

  # Routing
  go_router: ^14.0.2

  # Firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3

  # Networking
  dio: ^5.4.3

  # Payments
  in_app_purchase: ^3.2.0
  flutter_stripe: ^10.1.1 # For Stripe Checkout on web and mobile

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0 # For code generation with Riverpod

flutter:
  uses-material-design: true

  assets:
    - assets/tools/
